[project]
name = "quickdif"
dynamic = ["version"]
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "Beinsezii"}]
requires-python = ">= 3.11"
dependencies = [
    "accelerate",
    "compel",
    "diffusers>=0.30",
    "peft",
    "protobuf",
    "sentencepiece",
    "torch>=2.3",
    "transformers",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["quickdif"]

[tool.ruff]
line-length = 150

[tool.uv]
dev-dependencies = [
    "pytest",
]
