[project]
name = "quickdif"
dynamic = ["version"]
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Beinsezii" }]
requires-python = ">= 3.11"
dependencies = [
    "accelerate>=1.0.0",
    "compel>=2.0.3",
    "diffusers>=0.31.0",
    "peft>=0.13.1",
    "protobuf>=5.28.2",
    "sentencepiece>=0.2.0",
    "torch>=2.4.1",
    "torchao>=0.5.0",
    "transformers>=4.45.2",
]

[project.optional-dependencies]
navi-flash = [
    "flash-attn @ git+https://github.com/ROCm/flash-attention@howiejay/navi_support",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["quickdif"]

[tool.ruff]
line-length = 120

[dependency-groups]
dev = ["pytest>=8.3.3"]
