[project]
name = "quickdif"
dynamic = ["version"]
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "Beinsezii"}]
requires-python = ">= 3.11"
dependencies = [
    "accelerate>=0.33.0",
    "compel>=2.0.3",
    "diffusers>=0.30.0",
    "peft>=0.12.0",
    "protobuf>=5.27.3",
    "sentencepiece>=0.2.0",
    "torch>=2.4.0",
    "transformers>=4.44.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["quickdif"]

[tool.ruff]
line-length = 150

[tool.uv]
dev-dependencies = [
    "pytest",
]
