[project]
name = "quickdif"
dynamic = ["version"]
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "Beinsezii"}]
requires-python = ">= 3.11"
dependencies = [
    "torch >= 2",
    "diffusers >= 0.30",
    # "diffusers @ git+https://github.com/Beinsezii/diffusers.git@quickdif",
    "accelerate",
    "compel",
    "peft",
    "transformers",
    # Dependencies I don't explicitly use but aren't automatically pulled...
    #
    # Compel or pixart I forgot
    "omegaconf",
    # T5 SD3
    "protobuf",
    # Also compel or pixart I think
    "sentencepiece",
    # Why, diffusers? Why do you do this?
    "setuptools",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["quickdif"]

[tool.ruff]
line-length = 150

[tool.uv]
dev-dependencies = [
    "pytest",
]
