[project]
name = "quickdif"
dynamic = ["version"]
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "Beinsezii"}]
requires-python = ">= 3.11"
dependencies = [
    "torch >= 2.1",
    # "diffusers >= 0.27",
    # "diffusers @ git+https://github.com/Beinsezii/diffusers.git@quickdif",
    "diffusers @ https://github.com/huggingface/diffusers.git",
    "peft",
    "transformers",
    "accelerate",
    "omegaconf",
    "sentencepiece",
    "compel",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["quickdif"]

[tool.ruff]
line-length = 150
