[project]
name = "quickdif"
dynamic = ["version"]
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Beinsezii" }]
requires-python = ">= 3.12"
dependencies = [
    "accelerate>=1.7.0",
    "compel>=2.1.1",
    "diffusers>=0.33.1",
    "huggingface-hub[hf-xet]>=0.31.2",
    "peft>=0.15.2",
    "protobuf>=6.31.0",
    "sentencepiece>=0.2.0",
    "skrample[all]>=0.3.0",
    "torch>=2.7.0",
    "torchao>=0.10.0",
    "transformers>=4.51.3",
]

[project.optional-dependencies]
sageattn = ["sageattention==1.0.6"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["quickdif"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ["E402"]

[tool.pytest.ini_options]
python_files = "tests/*.py"

[dependency-groups]
dev = ["pytest>=8.3.3"]
