[project]
name = "quickdif"
dynamic = ["version"]
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "Beinsezii"}]
requires-python = ">= 3.11"
dependencies = [
    "torch >= 2.1",
    # "diffusers >= 0.28",
    "diffusers @ git+https://github.com/Beinsezii/diffusers.git@quickdif",
    # "diffusers @ git+https://github.com/huggingface/diffusers.git",
    "accelerate",
    "compel",
    "peft",
    "transformers",
    # Dependencies I don't explicitly use but aren't automatically pulled...
    "omegaconf", # Compel or pixart I forgot
    "protobuf", # T5 SD3
    "sentencepiece", # Also compel or pixart I think
    "setuptools", # Why, diffusers? Why do you do this?
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["quickdif"]

[tool.ruff]
line-length = 150
